front_refact_v.1
IlshatM/b3i-market pull request #109
Opened 2021-05-13 22:27 UTC by xNyXx

![image](https://user-images.githubusercontent.com/66951754/118195237-7ef1e780-b453-11eb-9376-36606e056d2b.png)

2021-05-14 13:06 UTC, IlshatM requested changes
1. ![image](https://user-images.githubusercontent.com/61285419/118274031-527ab180-b4cd-11eb-8b67-e5c4c8e5fc54.png)
2. ![image](https://user-images.githubusercontent.com/61285419/118274131-6e7e5300-b4cd-11eb-8d95-30839c6a99ae.png)

2021-05-14 13:16 UTC, voda2600 commented
Пофиксить пагинацию на скрине выше

2021-05-14 13:16 UTC, voda2600 commented
Уменьшить размер поиска

2021-05-15 22:23 UTC, xNyXx commented
![image](https://user-images.githubusercontent.com/66951754/118379591-230a9880-b5e4-11eb-8498-a9cfa7784bfb.png)
![image](https://user-images.githubusercontent.com/66951754/118379599-30278780-b5e4-11eb-92b1-97525d7ea420.png)
![image](https://user-images.githubusercontent.com/66951754/118379618-49303880-b5e4-11eb-87cd-bf05edb867c2.png)
![image](https://user-images.githubusercontent.com/66951754/118379626-50efdd00-b5e4-11eb-9a2c-a17f5e4efd9b.png)

![image](https://user-images.githubusercontent.com/66951754/118379605-387fc280-b5e4-11eb-9c36-43b9065945ed.png)
![image](https://user-images.githubusercontent.com/66951754/118379609-403f6700-b5e4-11eb-98dd-8fc657dd1871.png)

2021-05-16 17:21 UTC, voda2600 commented
![image](https://user-images.githubusercontent.com/24254731/118406317-38cf9a80-b684-11eb-8c7b-54126b21b88f.png)

2021-05-16 17:21 UTC, voda2600 commented
![image](https://user-images.githubusercontent.com/24254731/118406325-4127d580-b684-11eb-9cb4-f7fe09805860.png)

2021-05-16 17:22 UTC, voda2600 commented
Пагинация уходит вниз - и еще чуть криво влево уходит на второй строке

2021-05-16 17:22 UTC, voda2600 commented
![image](https://user-images.githubusercontent.com/24254731/118406361-69173900-b684-11eb-818e-ebdea510dfc9.png)

2021-05-16 17:23 UTC, voda2600 commented
Search кривой

2021-05-17 00:56 UTC, xNyXx commented
![image](https://user-images.githubusercontent.com/66951754/118419092-b5ce3480-b6c3-11eb-8a7d-db934eb7f480.png)
![image](https://user-images.githubusercontent.com/66951754/118419100-bb2b7f00-b6c3-11eb-8ad2-79fad6f5f4f4.png)
![image](https://user-images.githubusercontent.com/66951754/118419112-c8e10480-b6c3-11eb-96f7-b885900a5637.png)
![image](https://user-images.githubusercontent.com/66951754/118419122-ce3e4f00-b6c3-11eb-9440-cc07a14dd7fd.png)

2021-05-17 11:28 UTC, merged