adaptivity v1.1
IlshatM/b3i-market pull request #59
Opened 2021-04-05 19:15 UTC by xNyXx

2021-04-06 13:33 UTC, IlshatM requested changes
![image](https://user-images.githubusercontent.com/61285419/113718863-bdc6ac00-96f5-11eb-9e22-ef925ccfd68d.png)

2021-04-07 18:19 UTC, IlshatM requested changes
![image](https://user-images.githubusercontent.com/61285419/113915065-f7c3ab00-97e6-11eb-913f-ddcbb6ad7bad.png)

2021-04-11 21:24 UTC, voda2600 commented
Не, так не пойдёт, размер 100%, а главную страницу видно на 1/4
![image](https://user-images.githubusercontent.com/24254731/114321818-7ab96e00-9b25-11eb-879c-4b51b72e48df.png)

2021-04-11 21:43 UTC, xNyXx commented
там точно все так?
![image](https://user-images.githubusercontent.com/66951754/114322315-1a77fb80-9b28-11eb-8805-0eb6fa17bd8f.png)

2021-04-20 12:51 UTC, ByMyKolaps commented
Точно

2021-04-26 21:04 UTC, closed without merging